name: Build synth_one_click_installer.exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '>=2.17.1 <3.0.0'

    - name: Install dependencies
      run: dart pub get

    - name: Analyze code
      run: dart analyze --fatal-infos --fatal-warnings

    - name: Build executable
      run: dart compile exe bin/synth_one_click_installer.dart -o build/synth_one_click_installer.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: synth_one_click_installer
        path: build/synth_one_click_installer.exe
